### ISSUE TITLE
change README to just link to releases page?

### ISSUE THREAD

**Issue by jamesmanning** [jat255/teslacam-merge#1]
Current release is v0.1.15 but readme 'standalone binaries' section still links to v0.1.14 - might be easier to just link and say to download the zip or dmg files instead of needing to update the readme on every release?

**Comment by jat255** [comment]
I think you meant this issue for a different project, as mine doesn't have any releases!

**Comment by jamesmanning** [comment]
@jat255 sorry, yes, I meant it for ehendrix23/tesla_dashcam - my apologies! 😄

**Comment by jamesmanning** [comment]
@jat255 on a related note, though, the link to that other project says it requires a Python installation but the releases offered have Python and ffmpeg integrated so you don't need to have an existing Python install, you can just download and run it. 🤷‍♂
